version: "3.7"

networks:
  cl_net_overlay:
    driver: overlay
    external: true
services:
  celery_prefork:
    image: freelawproject/courtlistener:latest-celery
    depends_on:
      - cl-doctor
      - cl-disclosures
    deploy:
      resources:
        limits:
          cpus: "${CELERY_PREFORK_CONCURRENCY}"
          memory: "${CELERY_MEMORY:-1}GB"
      restart_policy:
        condition: on-failure
    volumes:
      - "${POSTGRESQL_SOCK:-/dev/null}:/var/run/postgresql"
      - "${DJANGO_MEDIA_ROOT:-/sata-old}:/storage"
    logging:
      driver: journald
    networks:
      - cl_net_overlay
    environment:
     - CELERY_QUEUES=celery
    env_file:
      - ../../.env

  celery_prefork_bulk:
    image: freelawproject/courtlistener:latest-celery
    depends_on:
      - cl-doctor
      - cl-disclosures
    deploy:
      resources:
        limits:
          cpus: "${CELERY_PREFORK_BULK_CONCURRENCY}"
          memory: "${CELERY_MEMORY:-1}GB"
      restart_policy:
        condition: on-failure
    volumes:
      - "${POSTGRESQL_SOCK:-/dev/null}:/var/run/postgresql"
      - "${DJANGO_MEDIA_ROOT:-/sata-old}:/storage"
    logging:
      driver: journald
    networks:
      - cl_net_overlay
    environment:
     - CELERY_QUEUES=batch0,batch1,batch2,batch3
    env_file:
      - ../../.env

  cl-doctor:
    image: freelawproject/doctor:latest
    container_name: "cl-doctor"
    networks:
      - cl_net_overlay
    logging:
      driver: journald

  cl-disclosures:
    image: freelawproject/disclosure-extractor:latest
    container_name: "cl-disclosures"
    networks:
      - cl_net_overlay
    logging:
      driver: journald
