name: Automate docker build and push
on:
  pull_request:
    branches: [ "main" ]
    types:
     - closed

env:
  AWS_REGION: us-west-2
  EKS_CLUSTER_NAME: courtlistener
  EKS_NAMESPACE: court-listener

jobs:
  build:
    # Build only merged PRs
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          make push --file docker/django/Makefile -e VERSION=${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Create Kubeconfig with AWS CLI
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
    - name: Get collect static assets and check unapplied migration exit code
      id: checkMigration
      run: |
        kubectl run ${{ github.sha }} -it -n ${{ env.EKS_NAMESPACE }} --image freelawproject/courtlistener:${{ github.sha }}-web-prod --overrides='
        {
          "spec": {
            "containers": [
              {
                "name": "${{ github.sha }}",
                "image": "freelawproject/courtlistener:${{ github.sha }}-web-prod",
                "command": [
                    "/bin/sh",
                    "-c",
                    "./manage.py collectstatic --noinput && ./manage.py migrate --check"
                ],
                "envFrom": [
                  {
                    "secretRef": {
                      "name": "cl-env"
                    }
                  }
                ]
              }
            ]
          }
        }
        '  && echo "::set-output name=exitCode::$(kubectl get  -n ${{ env.EKS_NAMESPACE }} pod/${{ github.sha }} -o jsonpath='{.status.containerStatuses[0].state.terminated.exitCode}')" && kubectl delete pod -n ${{ env.EKS_NAMESPACE }} ${{ github.sha }}

    - name: Check migration exit code
      run: |
        if [[ ${{ steps.checkMigration.outputs.exitCode }} -ne 0 ]]; then
          echo "Found unapplied migrations. Migrate manually, and re-run deployment."
          exit 1
        fi

    # Rollout new versions one by one...
    - name: Rollout cl-python
      run: kubectl set image -n ${{ env.EKS_NAMESPACE }} deployment/cl-python web=freelawproject/courtlistener:${{ github.sha }}-web-prod
    - name: Watch cl-python rollout status
      run: kubectl rollout status -n ${{ env.EKS_NAMESPACE }} deployment/cl-python

    - name: Rollout cl-celery-prefork
      run: kubectl set image -n ${{ env.EKS_NAMESPACE }} deployment/cl-celery-prefork cl-celery-prefork=freelawproject/courtlistener:${{ github.sha }}-celery
    - name: Watch cl-celery-prefork rollout status
      run: kubectl rollout status -n ${{ env.EKS_NAMESPACE }} deployment/cl-celery-prefork

    - name: Rollout cl-celery-prefork-bulk
      run: kubectl set image -n ${{ env.EKS_NAMESPACE }} deployment/cl-celery-prefork-bulk cl-celery-prefork-bulk=freelawproject/courtlistener:${{ github.sha }}-celery
    - name: Watch cl-celery-prefork-bulk rollout status
      run: kubectl rollout status -n ${{ env.EKS_NAMESPACE }} deployment/cl-celery-prefork-bulk

    - name: Update cronjobs
      run: |
        CRONJOB_NAMES=$(kubectl get cronjobs -n court-listener -o jsonpath='{.items.*.metadata.name}' -l image_type=web-prod);
        for name in $CRONJOB_NAMES; do
           kubectl set image -n ${{ env.EKS_NAMESPACE }} CronJob/$name job=freelawproject/courtlistener:${{ github.sha }}-web-prod;
        done;



# TODOS
# - Add requirement for PRs on main branch in Github.
# - Make sure that --check doesn't run migrations
# - Github short codes
